/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCHEMA_H_RPCGEN
#define _SCHEMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct __general_message {
	int type;
	char *resp;
};
typedef struct __general_message __general_message;

typedef __general_message general_message;

#define PROGRAM 0x31234568
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTH 1
extern  general_message * request_auth_1(char **, CLIENT *);
extern  general_message * request_auth_1_svc(char **, struct svc_req *);
#define REQUEST_ACC_TOKEN 2
extern  general_message * request_acc_token_1(char **, CLIENT *);
extern  general_message * request_acc_token_1_svc(char **, struct svc_req *);
#define APPROVE_REQUEST_TOKEN 3
extern  char ** approve_request_token_1(char **, CLIENT *);
extern  char ** approve_request_token_1_svc(char **, struct svc_req *);
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1(char **, CLIENT *);
extern  int * validate_delegated_action_1_svc(char **, struct svc_req *);
extern int program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTH 1
extern  general_message * request_auth_1();
extern  general_message * request_auth_1_svc();
#define REQUEST_ACC_TOKEN 2
extern  general_message * request_acc_token_1();
extern  general_message * request_acc_token_1_svc();
#define APPROVE_REQUEST_TOKEN 3
extern  char ** approve_request_token_1();
extern  char ** approve_request_token_1_svc();
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1();
extern  int * validate_delegated_action_1_svc();
extern int program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr___general_message (XDR *, __general_message*);
extern  bool_t xdr_general_message (XDR *, general_message*);

#else /* K&R C */
extern bool_t xdr___general_message ();
extern bool_t xdr_general_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCHEMA_H_RPCGEN */
