/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "schema.h"

bool_t
xdr___general_message (XDR *xdrs, __general_message *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_general_message (XDR *xdrs, general_message *objp)
{
	register int32_t *buf;

	 if (!xdr___general_message (xdrs, objp))
		 return FALSE;
	return TRUE;
}
